name: Create Miniconda Zips for Multiple Platforms

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run setup script
      run: node setup-python-env.js

    - name: List directories (Unix)
      if: runner.os != 'Windows'
      run: ls -la

    - name: List directories (Windows)
      if: runner.os == 'Windows'
      run: Get-ChildItem -Force

    - name: Zip anymatix directory (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $zipPath = "anymatix-windows.zip"
        if (Test-Path -Path "anymatix") {
          Compress-Archive -Path "anymatix" -DestinationPath $zipPath -Force
        } else {
          Write-Error "Error: anymatix directory not found"
          exit 1
        }
        echo "ZIP_PATH=$zipPath" >> $env:GITHUB_ENV

    - name: Zip anymatix directory (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          zipPath="anymatix-macos.zip"
        else
          zipPath="anymatix-linux.zip"
        fi
        
        if [ -d "anymatix" ]; then
          zip -r $zipPath anymatix
        else
          echo "Error: anymatix directory not found"
          exit 1
        fi
        echo "ZIP_PATH=$zipPath" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: anymatix-${{ runner.os }}
        path: ${{ env.ZIP_PATH }}
